import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { chromium } = require("C:/Users/Ram/AppData/Roaming/npm/node_modules/playwright");
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
page.on("console", (m) => { const t = m.text(); if (m.type() === "error" || m.type() === "warning") console.log(m.type(), t.slice(0, 500)); });
page.on("pageerror", (e) => console.log("PAGEERROR", e.message.slice(0, 500)));
await page.goto("http://localhost:3300/", { waitUntil: "load" });
await page.waitForTimeout(6000);
await page.locator("[data-testid=readout]").scrollIntoViewIfNeeded();
await page.waitForTimeout(3000);
await browser.close();
